### ISSUE TITLE
can I use pymple.nvim by gg 0.3.0?

### ISSUE THREAD

**Issue by micsama** [alexpasmantier/pymple.nvim#28]
[pymple.nvim]: Binary gg (0.3.0) is installed, but the version is either too old or too recent (min: 0.2.23, max: nil). Pl
 pymple.nvim. For more information, see [alexpasmantier/grip-grab](https://github.com/alexpasmantier/grip-grab)
 
 do I need to install gg==0.2 ?

**Comment by alexpasmantier** [comment]
Hi, you should be fine with version 0.3.

I'll update dependency checks tomorrow morning to take that into account.

**Comment by micsama** [comment]
> Hi, you should be fine with version 0.3.
> 
> I'll update dependency checks tomorrow morning to take that into account.

oh ,thanks so much

**Comment by alexpasmantier** [comment]
Fixed in https://github.com/alexpasmantier/pymple.nvim/pull/29 ✅

**Comment by rbhanot4739** [comment]
@alexpasmantier Still getting the this error on installing the plugin `binary gg is not installed, use PymplBuild ...`
